Many updates for the settings-helper branch with examples
python-sdbus/python-sdbus-networkmanager pull request #16
Opened 2022-04-26 17:55 UTC by bernhardkaindl

- Add testcase checking dbus_types and defaults using real connections
  from a running networkmanager (to be expanded to use json files too)

- The testcase fails if the output from settings.from_dbus.().to_dbus()
  differs from settings and also fails the dataclass delivers more(or
  less properties, or even a change in a value of a property.

- Change dbus_type of connection.timestamp from q to t (used by NetworkManager-1.30)

- Add generated NetworkManagerIpv6Settings, NetworkManagerProxySettings,
  NetworkManagerBridgeSettings, NetworkManagerWireguardSettings, NetworkManagerVpnSettings
  NetworkManagerEthernetSettings and NetworkManagerProxySettings,
  they are presented by the network connection profiles on my box.

- NetworkManngerSettings (typo and name clash) renamed to NetworkManagerConnectionProfile

- Export classes of sdbus_async/networkmanager/settings.py in __init__.py
- Convert example examples/async/list-connections-async.py
- Convert example examples/async/add-wifi-psk-connection-async.py

- Add generator tool generate-settings-dataclasses.py (based on
  NetWorkManager/generate-docs-nm-settings-docs-merge.py) - only for
  class generation, would be useful to generate dict classes too.

- {ipv4,ipv6}.{addresses,routes} are deprecated, don't import them.

- class NetworkManagerSettingsMixin.to_dbus(): Skip default values,
  not None (e.g. for bools, the real default can only be True or False)

- ConnectionProfile.connection is not optional: uuid and type are always
  needed.

- ConnectionProfileSettings: Use the generated default bool values

- Add class NetworkManagerConnectionWireguardPeers (tested with a real
  wireguard connection)

2022-04-26 17:59 UTC, bernhardkaindl commented
There is one major thing I don't like, which I guess is not possible to solve while still using dataclass as base class:

Say I want to update a network connection and want to change e.g. the WiFi PSK like so:
```py
    profile.wifi_security.psk = args.password
```
This triggers this mypy error:
```py
error: Item "None" of "Optional[WifiSecuritySettings]" has no attribute "psk"
```

The reason for this that the dataclass-based approach (has to use/uses) Optional[WifiSecuritySettings] to add "802-11-wifi-security" and all the other settings domains which are only present for specific connection types.

My idea for fixing this would be to create specific `ConnectionProfile` top-level classes for each type of connection, and in `.from_dbus()` check what the dict["connection"]["type"] indicates and then get the needed class for that connection_type.

To you see other possible ways to fix this issue?

PS: My Prodict and MetaDict-based approaches does not have this issue.

But it seems, this would be solvable using the different `ConnectionProfile` classes like `ConnectionProfileWireless`, `ConnectionProfileEthernet`, etc. - do you agree that this would be the way forward to fix that?

2022-04-26 19:00 UTC, igo95862 commented
> Say I want to update a network connection and want to change e.g. the WiFi PSK like so:

You can insert an assert so that mypy knows:

```python
assert profile.wifi_security is not None
```

2022-04-27 07:13 UTC, igo95862 commented
I will review this on weekend. A bit busy on workdays.

2022-04-30 17:42 UTC, igo95862 requested changes
I need to look in to the Network Manager source code to figure out what settings fields are actually required.

It seems like a common method of updating connections is to Read-Update-Write. I think I will add functions that help with that. (it will take a function Callable[[NetworkManngerSettings], None])

2022-04-30 17:42 UTC, igo95862 commented on sdbus_async/networkmanager/settings.py
> +    def to_dict(self) -> Dict[str, Dict[str, Any]]:
There is a `dataclasses.asdict` function in standard library. Maybe it can be leveraged here.

2022-04-30 21:49 UTC, bernhardkaindl commented on generate-settings-dataclasses.py
> +from __future__ import print_function
This file was originally based the NetworkManager script NetWorkManager/generate-docs-nm-settings-docs-merge.py, it's a leftover that has survived the conversion.

2022-04-30 21:53 UTC, bernhardkaindl commented on sdbus_async/networkmanager/__init__.py
> +    'NetworkManagerSettingsMixin',
No, when all ConnectionTypes are provided then not. But it would allow to add new ConnectionTypes without upgrading sdbus_async.networkmanager to a new version.

BTW, would you be ok with moving NetworkManagerSettingsMixin into a separage subpackage and then generate the ConnectionType-specific classes into separate files? (settings.py quickly became a bit hard to handle with so much code in it for me(

2022-05-01 07:22 UTC, bernhardkaindl commented on sdbus_async/networkmanager/objects.py
> +    async def connection_settings(self) -> ConnectionSettings:
I'm guessing you mean: Why not `self.connection_profile().connection`.

For an procedure or algorithm, I need to loop over all connections and check `connection.type`, `connection.interface-name` and `connection.timestamp`. (to check which profile which was the last profile which was activated on a given interface-name).

I wanted to avoid creating dataclasses for the full dictionary from get_settings have less overhead for this loop. Creating a single dataclass just for `.connection` would be enough for that use. No need to go over IPv4 etc.

2022-05-01 07:48 UTC, bernhardkaindl commented on sdbus_async/networkmanager/settings.py
> +        metadata={'dbus_name': 'addresses', 'dbus_type': 'deprecated{aau}'},
The notation `'deprecated{aau}'}` isn't used anywhere. I wanted to check for it but didn't manage it so far, I'd not needed.

I just wanted to let others avoid the "doh" moment that I had when updating the `address-data` of a connection, unfortunately it's not very intuitive what's happening with `addresses`:

When adding `ipv4.address-data`, and `ipv6.address-data` they kept the old `ipv4.addresses` and `ipv6.addresses` in full force because they would have broken all applications if they would have changed something with how `addresses` works.

So instead of creating new "v2" versions of all the calls which contain ipv4 and ipv6 interfaces, they just also return the data in the newer "address-data" structure.

But as stated in the documentation for the `addresses` state, when `address-data` is also passed to the `update()` call, `update()` ignores `address-data` in favour of `addresses`: This is to keep old clients which just modify `addresses` but also send `address-data` (because they got it from `get_settings()`) working.

But when I first tried to the sequence `get_settings()`, modify `address-data`, `update()` the IP addresses weren't updated. Same for `route-data` and `routes`, by the way.  

Only when I got to understand this little mess, I finally understood why one of the python examples in `NetworkManager` python deletes `addresses` and `routes` before calling `update()`.

Well-meaning to not let anybody else fall into this trap, if `update()` preferring `addresses` and `routes`, I added removing them then receiving these settings from get_settings(), so the users would not have to set them to None or in this case maybe rather '[]' to make `update()` take `address-data` and `route-data` instead.

2022-05-01 07:59 UTC, igo95862 commented on generate-settings-dataclasses.py
> +from __future__ import print_function
What was the license of original file?

2022-05-01 08:04 UTC, igo95862 commented on sdbus_async/networkmanager/settings.py
> +        metadata={'dbus_name': 'addresses', 'dbus_type': 'deprecated{aau}'},
I think when it is better to remove the `addresses` and `routes` all together and modify `from_dbus` to strip those fields. (liek this `dbus_dict.pop('addresses', None)`)

2022-05-01 08:06 UTC, bernhardkaindl commented on generate-settings-dataclasses.py
> +from __future__ import print_function
The original file has his: `# SPDX-License-Identifier: LGPL-2.1-or-later`. I think it would be ok to have it in `tools/contrib` or so, or I could submit it to NetworkManager upstream as an example for generating interface code.

There is no need to have it in the source of sdbus-networkmanager, but it's a nice tool to have somewher around, e.g. to update the dataclasses (preferably one file per dataclass) for new versions of NetworkManager (only for new fields, they won't intentionally break old code of course)

2022-05-01 08:14 UTC, bernhardkaindl commented on sdbus_async/networkmanager/settings.py
> +                unvarianted_options.pop(key)
Followup note for removing the deprecated `addresses` and `routes` fields. Here, I remove them in `from_dbus()` as suggested.

We can keep this and remove the change to use `deprecated{aau}` below (for which I didn't write any code)

2022-05-01 08:15 UTC, igo95862 commented on generate-settings-dataclasses.py
> +from __future__ import print_function
I was afraid the original file had some different license.

Just put it under `tools` folder.

> preferably one file per dataclass

I think two files: one is generated with all settings classes (`settings_generated.py`) and the other is handwritten classes such as `NetworkManagerSettingsMixin` (`settings.py`).

2022-05-01 08:18 UTC, igo95862 commented on sdbus_async/networkmanager/settings.py
> +                unvarianted_options.pop(key)
Do the `unvarianted_options.pop(key, None)`. It would return None if the key was not found.

2022-05-01 08:19 UTC, igo95862 commented on sdbus_async/networkmanager/settings.py
> +                unvarianted_options.pop(key)
Or even just:

```
unvarianted_options.pop("addresses", None)
unvarianted_options.pop("routes", None)
```

2022-05-01 08:20 UTC, igo95862 commented on sdbus_async/networkmanager/settings.py
> +                unvarianted_options.pop(key)
The only question is if there are similar named options.

I guess the `from_dbus` method can be subclassed for ConnectionSettings.

2022-05-01 08:26 UTC, bernhardkaindl commented on sdbus_async/networkmanager/settings.py
> +                unvarianted_options.pop(key)
Not ConnectionSettings but `Ipv4Settings` and `Ipv6Settings`, I'd say.

Or to follow the good practice of never duplicating the code - using subclass like this:
```py
class NetworkManagerIpAddressSettingsMixin(NetworkManagerSettingsMixin):
    def from_dbus(...):
```
```py
@dataclass
class Ipv4Settings(NetworkManagerIpAddressSettingsMixin):
   ...

@dataclass
class Ipv6Settings(NetworkManagerIpAddressSettingsMixin):
    ...
```

2022-05-01 08:37 UTC, bernhardkaindl commented on generate-settings-dataclasses.py
> +from __future__ import print_function
Good, that's a compromise (for me). It has some drawbacks from my viewpoint though:

* When we'd re-generate the generated classes, I could not opt to generate one a subset of the classes: We have to generate the complete generated file in one go and in case we made any manual tweaks to them, I'd have to revert all of them them manually or update the generation tool to generate these tweaks as well.

The special handling for ipvX.addresses and .routes is just a simple example.
```py
@dataclass
class Ipv4Settings(NetworkManagerIpAddressSettingsMixin):
   ...

@dataclass
class Ipv6Settings(NetworkManagerIpAddressSettingsMixin):
    ...
```

For class ConnectionSettings(), uuid, type and likely id are not Optional[str] but required, and other things like the order might be nice to be so that e.g. `interface-name` more on the top of the output when converting using to_dbus or to_dict/repr/asdict or so. But ConnectionSettings could be just in a separate file anyways to allow to better tweak it. Anyway, if the cost isn't to high, all generated classes in a subdir would have been nicest for me.

But all in one file isn't too bad either, and I guess we could code the tweaks into the generation tool as well.

2022-05-01 08:44 UTC, igo95862 commented on generate-settings-dataclasses.py
> +from __future__ import print_function
Ok. Put it in a separated folder module.

 `sdbus_async/networkmanager/settings/`

2022-05-01 12:25 UTC, bernhardkaindl commented on generate-settings-dataclasses.py
> +from __future__ import print_function
Thanks, I've pushed the first commit for that as a new PR #18, could you review it?

2022-05-17 11:13 UTC, bernhardkaindl commented
It got a lot of review feedback, thanks! The reviews in this PR are addressed or merged into #14, so this PR is not needed anymore.

2022-05-17 11:13 UTC, closed without merging