Latest update of the code-generation tool for settings-dataclasses:
python-sdbus/python-sdbus-networkmanager pull request #19
Opened 2022-05-05 11:37 UTC by bernhardkaindl

@igo95862 :+1: 
It's not perfect yet, but the most common cases shoult be covered now.
It needs the man/nm-settings-docs-dbus.xml from a build of NM.
    
It can be improved to the point where the settings sub-package is fully generated.

The 2nd commit are contains t the currently generated settings dataclasses.
    
Not perfect: In many files, some imports from tying are not used. It's a step leap forward.
    
This Just pushed for information, code-checking etc. Could be merged, but we can also generate the integration into the top-level class (it should be sent to stdout for now).

The not-generated files settings/base.py and settings/dataclasses.py could be moved up to the sdbus_async/networkmanager, but it's also fine where they are now.

I cannot look at it this until at least monday, so feel free to take, use, hack it it as you see fit. Cheers and thanks!

2022-05-05 12:06 UTC, igo95862 commented
> I cannot look at it this until at least monday, so feel free to take, use, hack it it as you see fit. Cheers and thanks!

Sure. I will look at it on weekend.

2022-05-08 16:26 UTC, igo95862 requested changes
I think the `Vlan` class is misssing from `settings/datatypes.py` and not being imported.

2022-05-08 16:26 UTC, igo95862 commented on sdbus_async/networkmanager/settings/x.py
> +class XSettings(NetworkManagerSettingsMixin):
I think a better name would be `Iee802.1x` or something similar. (also a better file name)

2022-05-08 16:26 UTC, igo95862 commented on tools/generate-settings-dataclasses.py
> +# SPDX-License-Identifier: LGPL-2.1-or-later
`# SPDX-License-Identifier: LGPL-2.1-or-later`

Should be first on top of the file. (there are a bunch of tools that rely on that)

2022-05-08 16:26 UTC, igo95862 commented on tools/generate-settings-dataclasses.py
> +    f.write("from dataclasses import dataclass, field\n")
Can you add `from __future__ import annotations`? Otherwise there will be issues with annotations between versions of python.

2022-05-08 16:26 UTC, igo95862 commented on sdbus_async/networkmanager/settings/bridge.py
> +    vlans: Optional[List[Vlans]] = field(
I don't see the `Vlans` class either be declared or imported.

2022-05-09 03:00 UTC, bernhardkaindl commented on sdbus_async/networkmanager/settings/x.py
> +class XSettings(NetworkManagerSettingsMixin):
Done

2022-05-09 03:00 UTC, bernhardkaindl commented on tools/generate-settings-dataclasses.py
> +# SPDX-License-Identifier: LGPL-2.1-or-later
Done

2022-05-09 03:02 UTC, bernhardkaindl commented on tools/generate-settings-dataclasses.py
> +    f.write("from dataclasses import dataclass, field\n")
Done. A remark AFAIK:

It should only be needed when a dataclass has a future reference, and so far I see no future reference.

Added anyways as I consider you to be the expert on that.

2022-05-09 03:02 UTC, bernhardkaindl commented on sdbus_async/networkmanager/settings/bridge.py
> +    vlans: Optional[List[Vlans]] = field(
Added.

2022-05-09 08:24 UTC, merged