Add example to create a new Ethernet connection
python-sdbus/python-sdbus-networkmanager pull request #4
Opened 2022-03-22 16:53 UTC by bernhardkaindl

2022-03-26 16:46 UTC, bernhardkaindl commented
@igo95862 This is also updated for `mypy --struct` and `flake8`.

I'd add the asyncio variant after the blocking variant passed review.

2022-03-26 17:37 UTC, igo95862 requested changes

2022-03-26 17:37 UTC, igo95862 commented on examples/block/add-eth-connection.py
> +    p.add_argument("-g", dest="gw", default="10.9.9.1/40000", help="gw/metric")
What do you think about using documentation IP ranges?

https://www.rfc-editor.org/rfc/rfc5737

For example, 192.0.2.0/24 .

2022-03-26 20:21 UTC, bernhardkaindl commented on examples/block/add-eth-connection.py
> +    p.add_argument("-g", dest="gw", default="10.9.9.1/40000", help="gw/metric")
Cool! Pushed with 192.0.2.0/24 !

2022-03-26 20:22 UTC, bernhardkaindl commented on examples/block/add-eth-connection.py
> +    p.add_argument("-g", dest="gw", default="10.9.9.1/40000", help="gw/metric")
I will add the async version next week when nothing else comes up before that!

2022-03-26 20:25 UTC, igo95862 approved these changes

2022-04-02 09:22 UTC, igo95862 requested changes
Would you mind rebasing against master so that commits e77fdf82c0ab4a3b2c798bdabbf05e0f573bcac0 and 8ba31e314bd6c91cd82a56d6be6284d91af70ec8 don't get double merged?

2022-04-02 11:37 UTC, bernhardkaindl commented
> Would you mind rebasing against master so that commits [e77fdf8](https://github.com/python-sdbus/python-sdbus-networkmanager/commit/e77fdf82c0ab4a3b2c798bdabbf05e0f573bcac0) and [8ba31e3](https://github.com/python-sdbus/python-sdbus-networkmanager/commit/8ba31e314bd6c91cd82a56d6be6284d91af70ec8) don't get double merged?

Done: Rebased #8 on new master and #4 on the rebased #8.

If you merge the rebased #8 using the "Rebase and merge" method of github (it's the 3rd of the 3 choices on how github can merge), you would not create a merge commit for #8 and it would be applied on master with no change, and then you can merge this #4 in one go without a need to rebase this one again on the otherwise created merge commit:

Ready to merge #8 by "Rebase and merge strategy, without creating a merge commit",
and then #4 after this merge off #8.

2022-04-02 11:58 UTC, bernhardkaindl commented
And of course I always accept github default of allowing project maintainers write access to the branch of the PR, so you can make any changes you want to the PR, including force-pushes with rebases.

And I can force-push the removal the commit for #8 from this PR, then you can merge #8 also with merge commit and this can be merged after it without rebase as the patch-context does not conflict.

2022-04-02 12:53 UTC, bernhardkaindl commented
@igo95862: Finished the rebase: It now only has a single commit on current master:

You can merge now, and it wil work when `get_connections_by_id()` like from #8 is merged too.

2022-04-03 11:36 UTC, merged