Add an example for updating a connection profile
python-sdbus/python-sdbus-networkmanager pull request #6
Opened 2022-03-23 12:07 UTC by bernhardkaindl

Update a property of a connection profile, looked up by connection id

2022-03-26 20:30 UTC, igo95862 requested changes

2022-03-26 20:30 UTC, igo95862 commented on examples/async/update-connection-async.py
> +        del settings["ipv4"]["addresses"]  # -> Use ["ipv4"]["address-data"]
I think `.pop()` method is better than `del`. `del` has some nasty side effects.

2022-03-26 20:30 UTC, igo95862 commented on examples/async/example_utilities_async.py
> +async def connection_by_id(conn_id: str) -> Optional[ConnectionSettingsTuple]:
This file shows a deficiency of the binds. They need more helper methods. (the functions that are actually not part of D-Bus interface)

I will look in to adding more of them tomorrow that can remove the need for this file.

2022-03-29 15:52 UTC, bernhardkaindl commented on examples/async/example_utilities_async.py
> +async def connection_by_id(conn_id: str) -> Optional[ConnectionSettingsTuple]:
Rebased and force-pushed on top of #8

2022-04-02 12:49 UTC, bernhardkaindl commented
@igo95862 rebased to current master so you can merge this PR without needing another rebase.

To work of course, it will need some form of `get_connections_by_id()` like from PR #8.

2022-04-03 11:35 UTC, merged